### ISSUE TITLE
Migrate from `react-native-windows-init` to `react-native init-windows` for new RNW projects

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#11920]
This item tracks all the work necessary to build a new simpler path for creating new RNW projects, with a primary focus of enabling the React Native New Architecture and golden-path supported scenarios.

### Tasks

```[tasklist]
#### Create named "old architecture" templates from existing UWP templates (in `/vnext`)
- [ ] https://github.com/microsoft/react-native-windows/issues/12147
- [ ] https://github.com/microsoft/react-native-windows/issues/12148
- [ ] https://github.com/microsoft/react-native-windows/issues/12149
- [ ] https://github.com/microsoft/react-native-windows/issues/12150
```

```[tasklist]
#### Create named "new architecture" templates (in `/vnext`)
- [ ] #11908
- [ ] https://github.com/microsoft/react-native-windows/issues/12171
- [ ] https://github.com/microsoft/react-native-windows/issues/12480
```

```[tasklist]
#### Create RNW CLI `init-windows` command  (in `/packages/@react-native-windows/cli`)
- [ ] https://github.com/microsoft/react-native-windows/issues/12151
- [ ] https://github.com/microsoft/react-native-windows/issues/12152
- [ ] https://github.com/microsoft/react-native-windows/issues/13459
- [ ] https://github.com/microsoft/react-native-windows/issues/13460
```

```[tasklist]
#### Stop using `react-native-windows-init`
- [ ] https://github.com/microsoft/react-native-windows/issues/13461
- [ ] https://github.com/microsoft/react-native-windows/issues/13462
```

```[tasklist]
#### Documentation / Samples
- [ ] https://github.com/microsoft/react-native-windows/issues/13394
- [ ] https://github.com/microsoft/react-native-windows/issues/13464
- [x] Remove references to deprecated CLI arguments (refer to using `ExperimentalFeatures.props` where appropriate)
- [ ] https://github.com/microsoft/react-native-windows/issues/13463
```

```[tasklist]
#### Deprecate and remove old code
- [ ] #11744
- [ ] https://github.com/microsoft/react-native-windows/issues/13465
- [ ] https://github.com/microsoft/react-native-windows/issues/13466
```

**Comment by jonthysell** [comment]
### RNW Init v1

#### RNW Init v1: Basics

- Customers start with a React Native app, typically having been created by the `npx react-native init` command
    - This includes the JS app code and native app hosts for iOS / Android
- To add Windows support via RNW, customers use the `npx react-native-windows-init` command
    - This adds our RNW dependencies and a native app host for Windows
- This new project functionality is primarily accomplished by these three RNW packages:
    1. `react-native-windows-init`
    1. `react-native-windows`
    1. `@react-native-windows/cli`

#### RNW Init v1: Package Versioning

![image](https://github.com/microsoft/react-native-windows/assets/10852185/ded41865-ba1d-4ba7-9396-a2c1068bd0ba)

#### RNW Init v1: CLI Arguments

Argument | Type | Default | Req. | Hidden | Description
-- | -- | -- | -- | -- | --
--help | bool | False | N | N | Show Help
--version | string | Auto¹ | Y¹ | N | Specify RNW version
--namespace | string | Auto² | Y² | N | Specify namespace for native code
--language | string | "cpp" | Y | N | Specify programming language C++ or C#
--projectType | string | "app" | N | N | Specify app or library (0.64+)
--useWinUI3 | bool | False | N | Y | Target WinUI 3.0 instead of UWP XAML
--useHermes | bool | False | N | Y | Use Hermes instead of Chakra (0.64+)
--experimentalNuGetDependency | bool | False | N | Y | Build against Microsoft.ReactNative   NuGet instead of source
--verbose | bool | False | N | N | Verbose output
--overwrite | bool | False | N | N | Overwrite files without prompting
--telemetry | bool | False | N | N | Send usage telemetry to MSFT
--useDevMode | bool | False | N | Y | Use local RNW clone
--nuGetTestFeed | string | "" | N | Y | Use specified NuGet test feed
--nuGetTestVersion | string | "" | N | Y | Use specified NuGet test version

¹: If unspecified, calculated based on existing project RN version
²: If unspecified, calculated based on existing project name

#### RNW Init v1: Code Flow

![image](https://github.com/microsoft/react-native-windows/assets/10852185/bb57954a-a118-4ac9-8293-9492e39da344)

**Comment by jonthysell** [comment]
### The Problems

1. The latest RNW Init must support all past versions of RNW
    1. The ABI between the packages is static
1. There are too many CLI arguments
    1. Produces a rather large matrix of combinations (not all supported)
    1. Not every argument is supported by every RNW version
    1. Experimental Features as args means we can’t deprecate args
1. Important changes to experimental features in the near/medium term
    1. Removing the WinUI3 template project
    1. Switch to Hermes as the default engine
    1. Switch to Fabric as the default architecture
    1. Switch to consuming NuGet instead of source
1. No way to invoke project init without RNW Init

**Comment by chrisglein** [comment]
@jonthysell FYI adding link to #13362. Resolve when appropriate.

**Comment by jonthysell** [comment]
I'm opening the remaining valid issues to be tracked toward milestones indivudually and moving this into next until it's all done

**Comment by Saadnajmi** [comment]
Curious why the change. Should macOS follow suit?

**Comment by jonthysell** [comment]
> Curious why the change. Should macOS follow suit?

Because the `react-native-windows-init` package needed to be evergreen for all RNW versions, we could never drastically change or remove args that older versions still supported (like --useHermes, which is the default for RNW >= 0.74, but not earlier, our prototpye winappsdk work which is now abandoned, etc.) so the command arg matrix was becoming this big mess of which version ranges support which args, etc.

So we built a RNW CLI command `react-native init-windows` to handle all the work for creating new projects (now with a cleaner API surface based on named templates). So once you add RNW to your project like any other dep, then the `init-command` is directly available and already directly tied to whichever RNW version you chose.

With that working, the old, evergreen `react-native-windows-init` command really only serves one purpose - to try to "guess" which version of RNW applies to your project and yarn add it to the package.json for you. It's easier to get rid of that than try to massage it even more to support the totally new API surface of our new commands.

But it's okay, now we can just tell devs "yarn add the RNW version you want" then you can use "react-native init-windows" at any time to restamp a windows template in your project folder. It's faster and more flexible.

As for what macos should do - do you need to support more than one type of template and/or you have a lot of args you allow to be passed into react-native-macos-init?

**Comment by jonthysell** [comment]
Closing this as the individual items track the remaining work.
