### ISSUE TITLE
Add Functional Tests for TextInput Component

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#12458]
Test cases should be added to the E2E test app (Fabric) to validate the following functionality scenarios. 

```[tasklist]
### Tasks
- [ ] TextInput should be editable when editable set to true.
- [ ] TextInput should not be editable when editable set to false.
- [ ] TextInput should take up to max length input when maxLength set.
- [ ] TextInput input should wrap to mulitple lines when multiline set to true.
- [ ] TextInput should trigger action upon onBlur.
- [ ] TextInput should trigger action upon onChange.
- [ ] TextInput should trigger action upon onChangeText.
- [ ] TextInput should trigger action upon onPressIn.
- [ ] TextInput should trigger action upon onPressOut.
- [ ] TextInput should trigger action upon onFocus.
- [ ] TextInput should trigger action upon onScroll.
- [ ] TextInput should trigger action upon onSelectionChange.
- [ ] TextInput placeholder text should update upon fast refresh.
- [ ] TextInput placeholder text color should update upon fast refresh.
- [ ] TextInput should not be editable when readOnly set to true.
- [ ] TextInput textAlign should change upon fast refresh.
- [ ] TextInput style should change upon fast refresh.
- [ ] TextInput should focus upon .focus() call.
- [ ] TextInput should lose focus upon .blur() call.
- [ ] TextInput text should clear upon clear() all.
- [ ] TextInput isFocused() should return true when the TextInput is focused.
- [ ] TextInput isFocused() should return false when the TextInput is not focused.

**Comment by chiaramooney** [comment]
As a "good first issue" the rows in the table represent individual function tests (usually for component properties).

Instructions for adding new functional tests here: https://github.com/microsoft/react-native-windows/wiki/E2E-Testing-(Fabric)#writing-functional-tests

Functional tests are usually fairly small, but some will be easier than others to implement.
