### ISSUE TITLE
Add Functional Tests for Button Component

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#12459]
Test cases should be added to the E2E test app (Fabric) to validate the following functionality scenarios.

```[tasklist]
### Tasks
- [ ] Button text should update on fast refresh.
- [ ] Button color should update on fast refresh.
- [ ] Button disabled status should update on fast refresh.
- [ ] Button should update relevant styling upon press.
```

**Comment by jonthysell** [comment]
As a "good first issue" the rows in the table represent individual function tests (usually for component properties).

Instructions for adding new functional tests here: https://github.com/microsoft/react-native-windows/wiki/E2E-Testing-(Fabric)#writing-functional-tests

Functional tests are usually fairly small, but some will be easier than others to implement.
