### ISSUE TITLE
Add Functional Tests for Flyout Component

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#12460]
Test cases should be added to the E2E test app (Fabric) to validate the following functionality scenarios.

```[tasklist]
### Tasks
- [ ] FlatList styles should update on fast refresh.
- [ ] FlatList contents should update on fast refresh.
- [ ] FlatList scrolling should update on fast refresh.
- [ ] FlatList footer should update on fast refresh.
- [ ] FlatList header should update on fast refresh.
```

**Comment by chiaramooney** [comment]
As a "good first issue" the rows in the table represent individual function tests (usually for component properties).

Instructions for adding new functional tests here: https://github.com/microsoft/react-native-windows/wiki/E2E-Testing-(Fabric)#writing-functional-tests

Functional tests are usually fairly small, but some will be easier than others to implement.
