### ISSUE TITLE
Add Functional Tests for Switch Component

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#12463]
Test cases should be added to the E2E test app (Fabric) to validate the following functionality scenarios.

```[tasklist]
### Tasks
- [ ] Switch should not toggle when disabled.
- [ ] Switch should fire onChange action when toggled.
- [ ] Switch should fire onValueChange action when toggled. 
- [ ] Switch thumbColor should update upon fast refresh.
- [ ] Switch trackColor should change upon fast refresh.
- [ ] Switch trackColor should not change upon hover.
- [ ] Switch value should match Switch visuals.
- [ ] Switch visuals should change upon toggle (on -> off).
- [ ] Switch visuals should change upon toggle (off -> on).
```
