### ISSUE TITLE
Add Functional Tests for Touchable Highlight

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#12465]
Test cases should be added to the E2E test app (Fabric) to validate the following functionality scenarios.

```[tasklist]
### Tasks
- [ ] TouchableHighlight should update style upon fast refresh.
- [ ] TouchableHighlight should update underlayColor upon fast refresh.
- [ ] TouchableHighlight should update activeOpacity upon fast refresh.
- [ ] TouchableHighlight should fire action upon press.
- [ ] TouchableHighlight should fire action upon onPressIn.
- [ ] TouchableHighlight should fire action upon onPressOut.
- [ ] TouchableHighlight should fire action upon onLongPress.
- [ ] TouchableHighlight should register press in clicked within hitSlop range.
- [ ] TouchableHighlight should not be interactable when disabled. 
```

**Comment by chiaramooney** [comment]
As a "good first issue" the rows in the table represent individual function tests (usually for component properties).

Instructions for adding new functional tests here: https://github.com/microsoft/react-native-windows/wiki/E2E-Testing-(Fabric)#writing-functional-tests

Functional tests are usually fairly small, but some will be easier than others to implement.
