### ISSUE TITLE
Add Functional Tests for ScrollView Component

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#12462]
Test cases should be added to the E2E test app (Fabric) to validate the following functionality scenarios.

```[tasklist]
### Tasks
- [ ] ScrollView should update styling upon fast refresh. 
- [ ] ScrollView should update header upon fast refresh.
- [ ] ScrollView should update footer upon fast refresh.
- [ ] ScrollView should update scroll direction upon fast refresh.
- [ ] ScrollView should scroll vertically when horizontal="false"
- [ ] ScrollView should scroll horizontally when horizontal="true"
- [ ] ScrollView should show end of list when scrollToEnd() is called.
- [ ] ScrollView should show desired location when snapTo* is called.
- [ ] ScrollViews should work when nested.
- [ ] Zoom?
```

**Comment by chiaramooney** [comment]
As a "good first issue" the rows in the table represent individual function tests (usually for component properties).

Instructions for adding new functional tests here: https://github.com/microsoft/react-native-windows/wiki/E2E-Testing-(Fabric)#writing-functional-tests

Functional tests are usually fairly small, but some will be easier than others to implement.
