### ISSUE TITLE
Add Functional Tests for View Component

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#12468]
Test cases should be added to the E2E test app (Fabric) to validate the following functionality scenarios.

```[tasklist]
### Tasks
- [ ] View should update style upon fast refresh.
- [ ] View should update underlayColor upon fast refresh.
- [ ] View should update activeOpacity upon fast refresh.
- [ ] View should fire action upon press.
- [ ] View should fire action upon onPressIn.
- [ ] View should fire action upon onPressOut.
- [ ] View should fire action upon onLongPress.
- [ ] View should register press in clicked within hitSlop range.
- [ ] View should not be interactable when disabled. 
```

**Comment by chiaramooney** [comment]
As a "good first issue" the rows in the table represent individual function tests (usually for component properties).

Instructions for adding new functional tests here: https://github.com/microsoft/react-native-windows/wiki/E2E-Testing-(Fabric)#writing-functional-tests

Functional tests are usually fairly small, but some will be easier than others to implement.

**Comment by frankcalise** [comment]
@chiaramooney I imagine we can extend the examples rendered inside of `ButtonExample.windows.js` is that correct? Add a set of buttons that utilize `onPressIn`, `onPressOut`, etc?

And then include the new test cases in `ButtonComponentTest.test.ts` - is my understanding correct?
