### ISSUE TITLE
Add Functional Tests for TouchableWithoutFeedback Component

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#12467]
Test cases should be added to the E2E test app (Fabric) to validate the following functionality scenarios.

```[tasklist]
### Tasks
- [ ] TouchableWithoutFeedback should update style upon fast refresh.
- [ ] TouchableWithoutFeedback should update underlayColor upon fast refresh.
- [ ] TouchableWithoutFeedback should update activeOpacity upon fast refresh.
- [ ] TouchableWithoutFeedback should fire action upon press.
- [ ] TouchableWithoutFeedback should fire action upon onPressIn.
- [ ] TouchableWithoutFeedback should fire action upon onPressOut.
- [ ] TouchableWithoutFeedback should fire action upon onLongPress.
- [ ] TouchableWithoutFeedback should register press in clicked within hitSlop range.
- [ ] TouchableWithoutFeedback should not be interactable when disabled. 


```

**Comment by chiaramooney** [comment]
As a "good first issue" the rows in the table represent individual function tests (usually for component properties).

Instructions for adding new functional tests here: https://github.com/microsoft/react-native-windows/wiki/E2E-Testing-(Fabric)#writing-functional-tests

Functional tests are usually fairly small, but some will be easier than others to implement.
