### ISSUE TITLE
Add Functional Tests for Text Component

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#12464]
Test cases should be added to the E2E test app (Fabric) to validate the following functionality scenarios.

```[tasklist]
### Tasks
- [ ] Text should update upon fast refresh.
- [ ] Text font should update upon fast refresh.
- [ ] Text size should update upon fast refresh.
- [ ] Text weight should update upon fast refresh.
- [ ] Text color should update upon fast refresh.
- [ ] Text styling should update upon fast refresh.
- [ ] Text line height should update upon fast refresh.
- [ ] Text alignment should updte upon fast refresh.
- [ ] Text font style should update upon fast refresh.
- [ ] Text background color should update upon fast refresh.
- [ ] Text transform should update upon fast refresh.
- [ ] Text borders should update upon fast refresh.
- [ ] Text foreground should not be overwritten when backgroundColor is set.
- [ ] Updates to a raw text node should not overwrite the TextBlock parent if it has only a single Span child inline. #7572
- [ ] Text should be marked dirty when descendant text nodes are added or removed
- [ ] Text should also be marked dirty when descendants of descendant virtual text nodes have changes to their text content.
- [ ] A raw text update to a non-optimized Text component should not call ClearValue on the TextBlock::TextProperty #11000
- [ ] Changes to the backgroundColor prop on virtual text nodes should update their corresponding TextHighlighters. #8408
- [ ] Changes to the underlying text should update the TextHighlighter ranges #8408
- [ ] Text numberOfLines should update upon fast refresh.
- [ ] Text should trigger action upon press.
- [ ] Text should trigger action upon long press.
```

**Comment by chiaramooney** [comment]
As a "good first issue" the rows in the table represent individual function tests (usually for component properties).

Instructions for adding new functional tests here: https://github.com/microsoft/react-native-windows/wiki/E2E-Testing-(Fabric)#writing-functional-tests

Functional tests are usually fairly small, but some will be easier than others to implement.
