### ISSUE TITLE
Add Functional Tests for Pressable Component

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#12461]
Test cases should be added to the E2E test app (Fabric) to validate the following functionality scenarios.

```[tasklist]
### Tasks
- [ ] Pressable should update border styling upon fast refresh.
- [ ] Pressable should update children upon fast refresh.
- [ ] Pressable should update disabled styling upon fast refresh.
- [ ] Pressable should update applicable styling upon hover. 
- [ ] Pressable should update applicable styling upon press. 
- [ ] Pressable should perform action upon press.
- [ ] Pressable should be able to track number of clicks.
- [ ] Pressable should perform action upon onPressIn.
- [ ] Pressable should perform action upon onPressOut.
- [ ] Pressable should perform action upon onLongPress.
- [ ] Pressable should not perform action upon press when disabled.
- [ ] Pressable behavior should change upon delayLongPress adjustment.
- [ ] Pressable should register onPress action when hit within hitSlop range.

```

**Comment by chiaramooney** [comment]
As a "good first issue" the rows in the table represent individual function tests (usually for component properties).

Instructions for adding new functional tests here: https://github.com/microsoft/react-native-windows/wiki/E2E-Testing-(Fabric)#writing-functional-tests

Functional tests are usually fairly small, but some will be easier than others to implement.
