### ISSUE TITLE
Create issues to track remaining host component properties that we need to implement for fabric

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#13183]
There are a variety of new issues tracking the remaining work to implement host component properties that we had in RNW paper and want to keep having in fabric. However the source list may have been out of date, and explicitly didn't include properties that RNW paper didn't already have.

We need a list of remaining properties that exist in fabric upstream and are not implemented in RNW fabric. From that list we can use a script to open tracking issues in RNW for each missing property.

> **Note:** we may still choose to not implement a given property in RNW fabric, but it's better to have that decision captured in a closed issue that can be re-opened later.

See also the old tracking issues here for properties that we ignored for Paper: https://github.com/microsoft/react-native-windows/issues/11135

```[tasklist]
### Tasks
- [ ] Create the list of properties View component that RN expects and do not work in RNW fabric
- [ ] Create the list of properties Text component that RN expects and do not work in RNW fabric
- [ ] Create the list of properties Image component that RN expects and do not work in RNW fabric
- [ ] Create the list of properties TextInput component that RN expects and do not work in RNW fabric
- [ ] Create the list of properties ScrollView component that RN expects and do not work in RNW fabric
- [ ] Create the list of properties Modal component that RN expects and do not work in RNW fabric
- [ ] Create the list of properties ActivityIndicator component that RN expects and do not work in RNW fabric
- [ ] Create the list of properties RefreshControl component that RN expects and do not work in RNW fabric
```

## Strategy

1. For each of the host components, look through their API page on reactnative.dev for the total list of supported properties expected
2. Determine whether the property works or not in RNW fabric. Strategies include:
    1. Checking the existing old parity lists for host component parity (#11135)
    2. Searching the RNW fabric code (usually under vnext/Microsoft.ReactNative/Fabric`
    3. Search the RN JS code (the property may be JS-only and not something we actually need to implement anything for
    4. Explicitly try using the property in test apps (e2e-test-app-fabric or otherwise)
3. Keep track of the properties that don't work in RNW fabric in a spreadsheet, including: Component Name, Property Name, Direct URL to Property in the RN Docs, and any Notes about what you discovered

After we have the lists, we can automate opening tracking items for each with the proper labels, etc.

**Comment by chiaramooney** [comment]
@danielayala94 Is this now complete with your new issues?

**Comment by danielayala94** [comment]
All core components implemented in Paper but not in Fabric were filed back in September. I may still have to decide what we want to do with Text Style, View Style, Layout and related props.
