### ISSUE TITLE
Validate next Hermes release will work with existing stable branches

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#13182]
As part of addressing the issues in #12982, @vmoroz is working on catching up hermes-windows with the upstream changes. This includes trying to do so in a way that enables our various stable branches (>= 0.71) to consume this next version of hermes-windows.

Right now, RNW 0.71 works with the current version of hermes-windows, 0.1.18, and RNW 0.72 and above have the aforementioned debugging issues. 

We want to actually verify the issues are fixed by Vladimir's work, i.e. that the new build will work with each stable branch, *before* we release the new version of hermes-windows. There may be some back and forth in this process as functionality may vary between different release branches.

```[tasklist]
### Tasks
- [ ] [0.71] Bump to the latest version of Hermes
- [ ] [0.72] Bump to the latest version of Hermes
- [ ] [0.73] Bump to the latest version of Hermes
- [ ] [0.74] Bump to the latest version of Hermes
- [ ] [main] Bump to the latest version of Hermes
```

## Strategy

1. @vmoroz will create a Microsoft.JavaScript.Hermes nuget package with the updated code
2. For each of the the branches for the tasks listed above, prep by:
    1. Have ready a new RNW Paper test app targeting that version of RNW
    2. Make sure UseHermes is enabled in ExperimentalFeatures.props
    3. Make sure the app is set to use `UseDirectDebugger` instead of `UseWebDebugger` in App.cpp
    4. Update (or create) the NuGet.config file with a local folder set as a nuget feed
    5. Update the app JS code to include a Button or something that can be explicitly invoked so there's a callback where variables are created and breakpoints can be set
    6. Have built the app once (to save time)
    7. Verify that you can attach a debugger (edge://inspect), set breakpoints in the callback mentioned above, and note what the current debugging experience looks like
3. When the drop is ready, put the nuget package in the local folder, then for each test app:
    1. Build the app with logging, making sure that this new local version was used (rather than the version from NuGet.org)
    2. Test the debugging experience again
    3. Report back to @vmoroz if the stable branch works, doesn't work, new issues, etc.
    4. Be ready for new drops, and/or to have to make code changes to the app's local copy of RNW
4. After it's been tested and we're in a good state, let @vmoroz publish a new official build
5. Use the task list above to create tasks and then PRs to update each stable branch with the new Hermes version + any changes you may have had to do to RNW code to make the new version work

```

**Comment by gabor-seres-sap** [comment]
We've encountered the following on 0.71-stable branch: https://github.com/microsoft/react-native-windows/issues/13312

**Comment by jonthysell** [comment]
Even though this is recurring work, adding to Next so it's not lost in the Backlog.

**Comment by TatianaKapos** [comment]
Reassigning to @vineethkuttan since he was most recently working on Hermes! Feel free to reassign to whoever makes sense but basically I would test the new hermes packages with debugging (but haven't recently since hermes debugging is broken) in the stable branches before we updated them.

**Comment by iamAbhi-916** [comment]
for 0.80 release tracking it here : https://github.com/microsoft/react-native-windows/issues/15015.
@jonthysell @TatianaKapos do we do it for [revious releases too or main is fine ?

**Comment by TatianaKapos** [comment]
@iamAbhi-916 I've done it for each of the supported stable branches
