### ISSUE TITLE
Integrate latest upstream RN versions of each stable branch into our RNW stable branches

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#13184]
RN upstream has a different matrix of stable branches they support than us, and lately they've been releasing more patch versions than we've kept caught up with. This can be a problem as RN app developers create new RN apps with the latest RN patch version of a stable release, then they add RNW which was tested on an older patch version.

At bare minimum we should assume we're only supporting developers on the latest patch versions of each stable branch, and I'm concerned there's noise in the issues opened against us because our stable branches have locked on older RN versions. So I think it's time for a pass over the stable branches, from RN 0.71 and up, doing the integrate into our stable branch, and therefore bumping our (minimum) dependency version on the latest patch from RN.

My hope is that these will be "easy" integrates as the upstream patches focus on ios/android specifics, but it's possible there may be some JS changes that we need to accept, which would be a great catch of our forked files drifting in a way that can lead to developer noise.

```[tasklist]
### Tasks
- [ ] [0.71] Integrate the latest RN 0.71
- [ ] [0.72] Integrate the latest RN 0.72
- [ ] [0.73] Integrate the latest RN 0.73
- [ ] [0.73] Integrate the latest RN 0.74
```

## Strategy

1. Follow the instructions on the https://github.com/microsoft/react-native-windows/wiki/Integration-Process
2. If the integrate doesn't look like it's changed anything, a quick adhoc test of e2e-test-app and the PR checks should be sufficient validation
3. If the integrate of a particular version seems to break things, bring it up right away so we can decide how to (de)prioritize it

**Comment by TatianaKapos** [comment]
I wonder if doing a pass on these branch every release would be a good cadance?
