### ISSUE TITLE
New apps created against 0.77+ should default to the new architecture

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#13683]
RN core in 0.76 will be defaulting new apps to the [new architecture](https://reactnative.dev/docs/the-new-architecture/landing-page). It stands to reason that RNW apps should also switch the default in 0.76. What's the challenge there? Well, the Fabric renderer for RNW remains [a work in progress](https://github.com/microsoft/react-native-windows/issues/12042). Core parity is decent but not complete, and more importantly fewer modules are going to be supported in this timeline.

So... why change the default? Because we're talking about new apps, not existing apps. And while there will be bumps for new apps, we'd rather set them on the right path for the future now rather than have them create a Paper app and then have to gut it moving to Fabric in the next version or two. And changing the default does not remove the option to fall back to Paper. If the new arch proves not viable for them, we can instruct them how to switch to Paper.

This issue should track what's needed to make this as good of an experience for everyone as we can.

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/react-native-windows/issues/13935
- [ ] https://github.com/microsoft/react-native-windows/issues/13936
- [ ] https://github.com/microsoft/react-native-windows/issues/13459
```

**Comment by jonthysell** [comment]
Closing this tracking issue as the individual items track the actual work.
