### ISSUE TITLE
Release RNW 0.63 (Checklist)

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#5594]
Working document to track status and work to release react-native-windows 0.63. Checklist is roughly based on the process we took for 0.62. This issue should be changed as these items are completed, new items come up, drivers change, etc.

**Legend**
- [ ] ⁉ Needs driver
- [ ] Work not started
- [ ] 🏃‍♂️ Work in progress
- [x] Work completed

## Milestones
- [x] **7/31:** Preview phase 1 
- [x] **8/14:** Preview phase 2
- [x] **Target 8/31:** Release

## Checklist

**Before Preview**
- [x] Draft GitHub release notes from commit log (NickGerleman )
- [x] Send mail to the team for additions/changes to release notes (NickGerleman)
- [x] Promote canary build to preview using [wiki instructions](https://github.com/microsoft/react-native-windows/wiki/How-to-promote-a-release) (NickGerleman)
- [x] Smoke test of functionality (NickGerleman) 
  - Some discussion here https://github.com/microsoft/react-native-windows/issues/5326
  - [x] Poke at RNTester
  - [x] Test new C++ app with run-windows
  - [x] Test new C++ app with VS
  - [x] Test new C# app with run-windows
  - [x] Test new C# app with VS
- [x] Push build to 0.63-stable branch and publish (NickGerleman )
- [x] Update GitHub release notes to use manually curated notes instead of a changelog (NickGerleman)
- [x] Post release notes internally (NickGerleman)
-----
**Preview Phase 1**
- [x] Ensure wiki page on release process is up to date with current thinking (NickGerleman) 
- [x] Send mail to the team reminding of dates + restrictions (NickGerleman)
- [x] Echo release notes into announcement/Tweet (stmoy )
- [x] Remind engineers to update API docs (chrisglein)
- [x] Move most issues targeting 0.63 to 0.64 (chrisglein)
- [x] Add "Blocking" label to any known showstopper regressions (chrisglein)
- [x] Determine and announce tentative dates for 0.64 (NickGerleman)
  - We have rough consensus on end of September as a target
- [ ] ❌ Drive validation of community modules (stmoy)
  - This is going to happen out-of-band for 0.63, want to engage owners earlier for 0.64
- [x] Integrate patch releases for React Native (NickGerleman) 
-----
**Preview Phase 2**
- [x] Modify CODEOWNERS in 0.63-stable to require changes go through @microsoft/react-native-windows-backport-triage (NickGerleman) 
- [x] Test samples against new version (jonthysell)
- [x] Send reminder mail to the team about phase 2 restrictions (NickGerleman)
- [x] Do a pass on API Docs (Team effort?)
- [x] Promote `latest` build to `legacy` using [wiki instructions](https://github.com/microsoft/react-native-windows/wiki/How-to-promote-a-release) (NickGerleman)
- [x] Ensure all issues marked with "Blocking Label" are fixed (chrisglein)
- [x] Ensure any backport-triage items needed in 0.63-stable are added (khalef1)
-----
**Release**
- [x] Update preview release notes with any changes from cherry-picked PRs (NickGerleman)
- [x] Update sample repos to new version (jonthysell)
- [x] Smoke test of functionality (jonthysell + NickGerleman) 
  - [x] Poke at RNTester
  - [x] Test new C++ app with run-windows
  - [x] Test new C++ app with VS
  - [x] Test new C# app with run-windows
  - [x] Test new C# app with VS
- [x] Promote `preview` build to `latest` using [wiki instructions](https://github.com/microsoft/react-native-windows/wiki/How-to-promote-a-release) (NickGerleman)
- [x] Update GitHub release notes to use manually curated notes instead of a changelog (NickGerleman)
- [x] Flip docs site to 0.63 (kikisaints)
- [x] Send out internal release announcement (stmoy) 
- [x] Send out external release announcement (kikisaints)
-----
**After Release**
- [ ] Hold a release process post-mortem to understand where we can improve (NickGerleman)
  - Going to discuss in conjunction with 0.64 planning

**Comment by TheSavior** [comment]
I'm new, so I have some noob questions. 😀 How do you choose what commit to update to? Is it the same commit that is used for a release on core? Do you plan to release each patch version as well or do you just jump to the latest patch release for that stable branch?

**Comment by NickGerleman** [comment]
This release is also a bit new for us as well, as its the first we've done with master aligned to nightly builds, and is also much closer to the initial release of the react-native version its using. I documented some thoughts and process here though https://github.com/microsoft/react-native-windows/wiki/How-to-promote-a-release 

My current thoughts are to align to 0.63.0. The safest thing to do would be to align to the first RC of 0.63, since it will be almost exactly what our branch is currently based on. Last I looked the commits that happened between first RC and 0.63.0 were unlikely to affect us, so aligning to something non-prerlease seems like a potentially better option. I or someone else would integrate 0.63.1, etc into the branch after.

RNW is a little bit sketch with RN patch releases in general right now. We have been allowing any version of RN with the same major + minor version as a peer dependency. This means we potentially mix and match files from different patch levels when using react-native-windows. The logic here was that the delta between patches is usually small, and aligning patch versions would be painful, so the risk is worth it. We haven't been able to test this in practice though since we've been far enough behind there haven't been new RN patches after we've released.

**Comment by asklar** [comment]
I think this week is the last week of the release, but it is also hackathon week, so I worry about the ability of folks to be able to jump into pressing issues.
I wonder if we should delay release by a week, and make sure in the future we include events like hackathon and holidays into it. Thoughts?

Thanks,
-Alex
Want to debug CMD scripts? Now you can<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fosgwiki.com%2Fwiki%2FDebugging_CMD_batch_scripts&data=02%7C01%7Casklar%40microsoft.com%7C63a4d82b2ed84da97fe308d79a0bb4db%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637147247374602630&sdata=GLXAVzgBgrLin8INpPyNJc%2FrffITtXUPx34Ww8Uhi5k%3D&reserved=0>

**Comment by NickGerleman** [comment]
(edited the above comment to trim out the email gunk GitHub added)

The thought of delaying the release has definitely crossed my mind. The overlap with hackathon is something that I personally didn't realize and I'm not sure the others did either. This week and last week also ended up being the dates I picked out 8 months ago for a 2 week incident response rotation for Office stuff, so I've definitely been pretty busy 🙂.

Ultimately I think delaying would do more harm than good though. Changing dates creates confusion, especially after we've communicated them to internal partners. In the past we've discussed the preview as having a pretty low-bar (basically, only block if there were catastrophic issues), so we don't expect everything to be perfect. This is also why we have a two week "free period" without triage after we branch, to allow folks to fixup anything that might have been introduced.

A big goal of announcing dates ahead of time is to let engineers know when it's safe to merge large changes that might have a long-tail, vs when to wait. Another purpose is to help partners know when things are coming, especially those still on ReactUwp who need to invest time in upgrading. We tentatively decided early July to branch EOM. The date was chosen as a balance of keeping up with RN Core, but still allowing enough time to get our own payload in. We started communicating tentative dates shortly after, and Chris checked with some folks on the Windows side before we announced them more broadly.

The process of deciding on dates for 0.63 felt a bit more last-minute than I would like for the future. Part of the release checklist I have above is to come up with 0.64 dates much earlier, to create better clarity, and to allow more time for discussion. The tentative schedule has been to branch every two months while catching up to RN core, and we've been needing to build muscle we haven't had around planning release N when stabilizing N-1. We're approaching the point of uncertainty for core alignment, which is actually a good thing since it means we're closer to being caught up. @TheSavior I would assume yes, but do you know if we expect core to create 0.64-stable within the next two months?

**Comment by NickGerleman** [comment]
And, we're out! Thanks for all the great work from @jonthysell @harinikmsft @kikisaints @chrisglein @stmoy and anyone else who I missed. Lets try to keep future releases going this smoothly 🙂.
