### ISSUE TITLE
Update react native directory to identify <0.60 (legacy) modules (or convert all those to modern RNW)

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#6282]
Query of all modules that support Windows: https://reactnative.directory/?windows=true
Without version compatibility information, it's unclear that about half of those won't work with current versions of RNW (once known as "vnext"). Here's a snapshot of ones that need evaluation:

- [ ] [react-native-code-push](https://github.com/microsoft/react-native-windows/projects/23#card-28520564)
- [ ] react-native-jalali-datepicker
- [ ] [react-native-device-info](https://github.com/microsoft/react-native-windows/issues/5311)
- [ ] react-native-track-player
- [ ] [react-native-file-viewer](https://github.com/microsoft/react-native-windows/issues/5077)
- [ ] use-count-up
- [ ] react-native-rooster
- [ ] react-native-linear-gradient
- [ ] react-native-sensitive-info
- [ ] [react-native-sqllite-storage](https://github.com/microsoft/react-native-windows/issues/6033)
- [ ] react-native-offline
- [ ] react-native-woodpicker
- [ ] stacks
- [ ] triangle
- [ ] react-native-sound
- [ ] react-native-event-source

**Comment by chrisglein** [comment]
Should we remove them as being tagged for windows in the meantime to reduce confusion?
We're going to target converting these modules with priority so hopefully this is just a point in time... but we don't know how long this point in time will last.
In the future we're going to run into this problem anew with WinUI3 where it'll need to known whether a module is compatible or not (or do we have to add support to all of them).
Are there other considerations with binary distribution?
It doesn't sound like there's a lot of appetite to add min/max version metadata to the directory website.

@stmoy this seems like we need more discussion, can you drive that?

**Comment by chrisglein** [comment]
@stmoy You have an updated list for what the status of these. Can you check off the ones that are converted? Then we can use the remainder to build a list to potentially remove Windows support and remove their listing from the directory (if there's no interest in updating the module).
