### ISSUE TITLE
RNW 0.64 Release Discussion

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#6494]
WIP Changelog here: https://github.com/microsoft/react-native-windows/releases/tag/react-native-windows_v0.64.0-preview.1

## Milestones
- **11/25:** Release 0.64.0-preview.1
- **1/15:** Changes in 0.64-stable require triage
- **1/29:** Release Target

## Blocking Issues
- re-generate API docs for 0.64 #6806 (asklar)
- Integrate final bits from react-native@0.64.0

## Checklist

**Legend**
- [ ] ⁉ Needs driver
- [ ] Work not started
- [ ] 🏃‍♂️ Work in progress
- [x] Work completed

**Before Preview**
- [x] Draft GitHub release notes from commit log (NickGerleman)
- [x] Promote canary build to preview using [wiki instructions](https://github.com/microsoft/react-native-windows/wiki/How-to-promote-a-release) (NickGerleman)
- [x] Smoke test of functionality (NickGerleman) 
  - Some discussion here https://github.com/microsoft/react-native-windows/issues/5326
  - [x] Poke at RNTester
  - [x] Test new C++ app with run-windows
  - [x] Test new C++ app with VS
  - [x] Test new C# app with run-windows
  - [x] Test new C# app with VS
  - [x] Test new C++ app with Hermes
- [x] Push build to 0.63-stable branch and publish (NickGerleman )
- [x] Update GitHub release notes to use manually curated notes instead of a changelog (NickGerleman)
- [x] Post release notes internally (NickGerleman)
-----
**After Preview**
- [x] Send mail to the team reminding of dates + restrictions (NickGerleman)
- [x] Move most issues targeting 0.64 to 0.65 (chrisglein)
- [x] Add "Blocking" label to any known showstopper regressions (chrisglein)
- [x] Test updated gallery app (stmoy)
- [x] Test updated samples (jonthysell)
- [x] Do a pass on API Docs (ngerlem)
- [x] Integrate patch/prerelease releases for React Native (NickGerleman) 
- [x] Modify CODEOWNERS in 0.63-stable to require changes go through @microsoft/react-native-windows-backport-triage (NickGerleman) 
- [x] Send reminder mail to the team about backport triage (NickGerleman)
-----
**Before Release**
- [x] Ensure any community typing changes happen (rectified95?)
- [x] Test samples against newest version (jonthysell)
- [x] Ensure doc issues are addressed (NickGerleman)
- [x] Promote `latest` build to `legacy` using [wiki instructions](https://github.com/microsoft/react-native-windows/wiki/How-to-promote-a-release) (NickGerleman)
- [x] Ensure all issues marked with "Blocking Label" are fixed (chrisglein)
-----
**Release**
- [x] Update preview release notes with any changes from cherry-picked PRs (NickGerleman)
- [x] Update sample repos to new version (jonthysell)
- [x] Update gallery to a new version (chiara)
- [x] Smoke test of functionality (NickGerleman) 
  - [x] Poke at RNTester
  - [x] Test new C++ app with run-windows
  - [x] Test new C++ app with VS
  - [x] Test new C# app with run-windows
  - [x] Test new C# app with VS
  - [x] Test new C++ app with Hermes
- [x] Promote `preview` build to `latest` using [wiki instructions](https://github.com/microsoft/react-native-windows/wiki/How-to-promote-a-release) (NickGerleman)
- [x] Update GitHub release notes to use manually curated notes instead of a changelog (NickGerleman)
- [x] Flip docs site to 0.64 (kikisaints/jonthysell)
- [x] Send out internal release announcement (NickGerleman) 
- [x] Send out external release announcement (kikisaints)

**Comment by rectified95** [comment]
If we're mentioning Text borders, let's also mention backgroundColor for it.

**Comment by rectified95** [comment]
I wanted to add Pressable typings, but then focused on upstreaming the change. Since that work has been held up, I can add Windows-specific typings for 0.64.

**Comment by NickGerleman** [comment]
> I wanted to add Pressable typings, but then focused on upstreaming the change. Since that work has been held up, I can add Windows-specific typings for 0.64.

@alloy do you know current plans for updating DefinitelyTyped Typings for RN 0.64? Haven't seen a PR for it yet.

**Comment by chrisglein** [comment]
Down to the last 2 items on the checklist. Tracking them here:
- [Update gallery to a new version](https://github.com/microsoft/react-native-gallery/issues/38) @chiaramooney 
- [Send out external release announcement](https://github.com/microsoft/react-native-windows-samples/pull/376) @kikisaints

**Comment by NickGerleman** [comment]
Working on pushing out the announcement now

**Comment by NickGerleman** [comment]
Announcement is out https://microsoft.github.io/react-native-windows/blog/2021/03/16/64updates

**Comment by NickGerleman** [comment]
Going to close this out. Last item was gallery 0.64, which there is now a PR out for.
