### ISSUE TITLE
RNW 0.65 Release Status

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#7679]
Changelog: https://github.com/microsoft/react-native-windows/issues/7679#issuecomment-845928761
Upstream issue: https://github.com/react-native-community/releases/issues/223

The milestones below are based on those set for the upstream release and are subject to change.

## Milestones
1. **Upstream RC:** Week of May 25th
1. **Release 0.65.0-preview.1**:  Week of May 25th
1. **Changes in 0.65-stable require triage**:  June 4th
1. **Release target**:  ???

## Important Issues

0.65 issues: https://github.com/microsoft/react-native-windows/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.65

**Blocking**
- None 😀

## Commits of Interest (Breakage Potential)
- https://github.com/microsoft/react-native-windows/commit/63d5e9fdecb5dd009fb839899f04747c63251e36

## Checklist

**Before Preview**
- [x] Draft GitHub release notes from commit log (NickGerleman)
- [x] Snap Hermes-Windows release (mganandraj)
- [x] Promote canary build to preview using [wiki instructions](https://github.com/microsoft/react-native-windows/wiki/How-to-promote-a-release) (NickGerleman)
- [x] Push build to 0.65-stable branch and publish (NickGerleman)
  - [x] Enable CI schedule for 0.65-branch of [CI pipeline](https://dev.azure.com/ms/react-native-windows/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=468&view=Tab_Triggers)
  - [x] Update [dashboard @ms](https://dev.azure.com/ms/react-native-windows/_dashboards/dashboard/28deb05d-f5bb-43e6-8aa9-36ad5e5476fb) with an entry for `CI 0.65`
  - [x] Add release schedule for 0.65-stable of [publish pipline](https://dev.azure.com/microsoft/ReactNative/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=63081&view=Tab_Triggers)
  - [x] Update [dashboard @microsoft](https://dev.azure.com/microsoft/ReactNative/_dashboards/dashboard/8ea77a11-83e2-493a-873f-9cd4562f213d) with an entry for `Publish 0.65`
- [x] Update GitHub release notes to use manually curated notes instead of a changelog (NickGerleman)
- [x] Post release notes internally (NickGerleman)
-----
**After Preview**
- [x] Send mail to the team reminding of dates + restrictions (NickGerleman)
- [x] Move most issues targeting 0.65 to 0.66 (chrisglein)
- [x] Test updated gallery app (chiara)
- [x] Do a pass on API Docs (???)
- [x] Integrate patch/prerelease releases for React Native (NickGerleman) 
- [x] Modify CODEOWNERS to require changes go through @microsoft/react-native-windows-backport-triage (NickGerleman) 
- [x] Send reminder mail to the team about backport triage (NickGerleman)
-----
**Before Release**
- [ ] Ensure any community typing changes happen (NickGerleman)
- [x] Ensure doc issues are addressed (???)
- [x] Promote `latest` build to `legacy` using [wiki instructions](https://github.com/microsoft/react-native-windows/wiki/How-to-promote-a-release) (NickGerleman)
- [x] Ensure all issues marked with "Blocking Label" are fixed (chrisglein)
-----
**Release**
- [x] Update preview release notes with any changes from cherry-picked PRs (NickGerleman)
- [ ] Update sample repos to new version (jonthysell), see [upgrade procedure](https://github.com/microsoft/react-native-windows-samples/blob/master/samples/README.md#upgrade-procedure)
- [ ] Update gallery to a new version (chiara)
- [x] Promote `preview` build to `latest` using [wiki instructions](https://github.com/microsoft/react-native-windows/wiki/How-to-promote-a-release) (NickGerleman)
- [x] Update GitHub release notes to use manually curated notes instead of a changelog (NickGerleman)
- [x] Flip docs site to 0.65 (???)
- [x] Update the CI to tell the API doc generation tool to use the 0.65 prefix
- [x] Send out internal release announcement (NickGerleman) 
- [x] Tweet/social (stmoy)

**Comment by dannyvv** [comment]
Added more fine grained steps for setting up the release pipelines when creating the forked branch:
- [ ] Push build to 0.65-stable branch and publish (NickGerleman)
  - [ ] Enable [CI yaml](https://github.com/microsoft/react-native-windows/blob/master/.ado/continuous.yml) for 0.65-stable branch
  - [ ] Update [dashboard @ms](https://dev.azure.com/ms/react-native-windows/_dashboards/dashboard/28deb05d-f5bb-43e6-8aa9-36ad5e5476fb) with an entry for `CI 0.65`
  - [ ] Add release schedule for 0.65-stable of [publish pipline](https://dev.azure.com/microsoft/ReactNative/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=63081&view=Tab_Triggers)
  - [ ] Update [dashboard @microsoft](https://dev.azure.com/microsoft/ReactNative/_dashboards/dashboard/8ea77a11-83e2-493a-873f-9cd4562f213d) with an entry for `Publish 0.65`

**Comment by asklar** [comment]
[ ] Update the CI to tell the API doc generation tool to use the 0.65 prefix

**Comment by NickGerleman** [comment]
> * [ ]  Update the CI to tell the API doc generation tool to use the 0.65 prefix

Where does this happen, and can we change the pipelines logic to not need it? I did a pass a while back to remove hardcoded versions, or move any release-cutting bits into the `@rnw-scripts/promote-release` script. Would be great to continue the tradition.

**Comment by asklar** [comment]
for 0.64 this happens [here](https://github.com/microsoft/react-native-windows/commit/187a6be31f685a5ea6f5404a2024c926b9ad445a#diff-6a3fb2d860be9b6a806db5a541290fe9ee6587935cc508750d89e77d7a19c3ecR83)
for 0.65 you'd just add /apiVersion 0.65 to the command line

**Comment by NickGerleman** [comment]
Assigned an issue over to you. I am hoping to cut the branch end of week if you want to manually update it, but I would highly recommend using one of the available solutions to not need to make manual edits every time we cut a release.

**Comment by NickGerleman** [comment]
Current changelog draft below:

---

We're excited to release our first preview build of `react-native-windows` 0.65! This build targets `react-native` 0.65.0-rc.1 and above. There have been many changes to both `react-native-windows` and `react-native` itself and we would love your feedback on anything that doesn't work as expected.

## What's new

- **Hermes debugging and profiling:** You can now debug and profile heap usage for your JavaScript running on Hermes for Windows. See [this document](https://github.com/microsoft/react-native-windows/blob/fedcbf60574ae67ec8a30f3f0c015f4070ee2f26/docs/inspector.md) for details. *(This change is currently gated behind the `HERMES_ENABLE_DEBUGGER` preprocessor definition.)*

- **New component capabilities:** We've added Windows support for some existing, and some all new properties, including:
  - `<Button>`: `tabIndex`
  - `<Pressable>`: `onKeyDown`/`onKeyUp`
  - `<TextInput>`: `autoFocus`, `clearTextOnSubmit`, `submitKeyEvents` 
  - `<Image>`: SVG data URI in `source`

- **TraceLogging based ETW events:** We now expose the ability to record ETW events for various framework actions. See [here](https://github.com/microsoft/react-native-windows/blob/fedcbf60574ae67ec8a30f3f0c015f4070ee2f26/docs/tracing.md) for details.

- **More consistent styling for \<Button\>:** The stock `<Button>` component has been updated with a look-and-feel consistent with other Windows controls.

- **FlatList performance improvements:** Several performance issues causing excessive renders when using FlatList have been fixed.

- **Opt-in fast builds:** Enabling the `RNW_FASTBUILD` MSBuild property enables larger PCH's. This leads to a much faster build, at the expense of higher system requirements to build successfully.

- **IViewManagerCreateWithProperties:** View managers may implement `IViewManagerCreateWithProperties` to receive properties at the time of view creation, simplifying cases where different properties may lead to different native views.

- **Bug-fixes and improvements:** The above just scratches the surface on the work that has been happening! We've been continually making bug fixes and improvements across the project.

## Breaking Changes

- **Legacy WebSocket implementation:** We introduced a new WebSocket stack in 0.64, along with the `QuirkSettings::SetUseLegacyWebSocketModule` function to opt-out of it. This setting is now removed, and the new implementation is always used.

- **32-bit ARM support:** We removed support for 32-bit ARM processors, which are used on some Windows IoT core devices.

- **WinUI 3 Islands:** React Native Windows now targets WinUI 3 preview 4 when set to use WinUI 3. This requires [changes](https://github.com/microsoft/react-native-windows/pull/7135) for applications using WinUI 3 with XAML Islands.

## Upgrading

The most surefire way to upgrade from a previous version is to generate a new project targeting 0.65 using `react-native-windows-init` and copy over your project content. In the future we would like to provide diffs to help make this easier in the style of `react-native-upgrade-helper`.

**Comment by acoates-ms** [comment]
Do we want to point people to https://github.com/acoates-ms/rnw-diff for the update diff?

And is HERMES_ENABLE_DEBUGGER set by default in debug builds of the nuget?  Or is debugging not possible when using the nuget

**Comment by NickGerleman** [comment]
I confirmed with AndnadrajHERMES_ENABLE_DEBUGGER is defined by the Hermes-Windows NuGet package, and does not need to be manually set.

Hermes + experimental NuGet package are not compatible in general at the moment.

**Comment by NickGerleman** [comment]
Pointing folks to rnw-diff seems like a good idea.

**Comment by NickGerleman** [comment]
I tentatively made a slightly controversial change to the checklist. I removed the manual checklist 😮

Realistically I do not think it has been providing value compared to time put in. I haven't seen breaks over the last 2-3 releases, with the last bug I know of being an issue with `yarn` and the evergeeen `react-native-windows-init` when we had much less usage.

If we see a break, we should try to categorize it as "we need test coverage" or "the feedback systems are working".

**Comment by NickGerleman** [comment]
This could be an egg on our face moment, but I think we have enough systems at this point to prevent that from reaching our final release. We will have to see.

**Comment by chrisglein** [comment]
RN core has released! [v0.65.0](https://github.com/facebook/react-native/releases/tag/v0.65.0) 🍾

**Comment by NickGerleman** [comment]
We're out! https://github.com/microsoft/react-native-windows/releases/tag/react-native-windows_v0.65.0

**Comment by NickGerleman** [comment]
All of the remaining work is in flight or has new issues, so I'm going to close this out!
