### ISSUE TITLE
0.66 Release Status

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#8509]
Changelog: TBD
Upstream issue: https://github.com/react-native-community/releases/issues/246

The milestones below are based on those set for the upstream release and are subject to change.

## Milestones
1. **Upstream RC:** Out
1. **Release 0.66.0-preview.1**:  9/6
1. **Changes in 0.65-stable require triage**:  9/20
1. **Release target**:  ???

## Important Issues

0.66 issues: https://github.com/microsoft/react-native-windows/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.66

**Blocking**
- TBD

## Checklist

**Before Preview**
- [ ] Draft GitHub release notes from commit log (NickGerleman)
- [ ] Snap Hermes-Windows release (mganandraj)
- [ ] Promote canary build to preview using [wiki instructions](https://github.com/microsoft/react-native-windows/wiki/How-to-promote-a-release) (NickGerleman)
- [ ] Push build to 0.66-stable branch and publish (NickGerleman)
  - [ ] Enable CI schedule for 0.66-branch of [CI pipeline](https://dev.azure.com/ms/react-native-windows/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=468&view=Tab_Triggers)
  - [ ] Update [dashboard @ms](https://dev.azure.com/ms/react-native-windows/_dashboards/dashboard/28deb05d-f5bb-43e6-8aa9-36ad5e5476fb) with an entry for `CI 0.66`
  - [ ] Add release schedule for 0.65-stable of [publish pipline](https://dev.azure.com/microsoft/ReactNative/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=63081&view=Tab_Triggers)
  - [ ] Update [dashboard @microsoft](https://dev.azure.com/microsoft/ReactNative/_dashboards/dashboard/8ea77a11-83e2-493a-873f-9cd4562f213d) with an entry for `Publish 0.66`
- [ ] Update GitHub release notes to use manually curated notes instead of a changelog (NickGerleman)
- [ ] Post release notes internally (NickGerleman)
-----
**After Preview**
- [ ] Send mail to the team reminding of dates + restrictions (NickGerleman)
- [ ] Move most issues targeting 0.66 to 0.67 (chrisglein)
- [ ] Test updated gallery app (chiara)
- [ ] Do a pass on API Docs (???)
- [ ] Integrate patch/prerelease releases for React Native (NickGerleman) 
- [ ] Modify CODEOWNERS to require changes go through @microsoft/react-native-windows-backport-triage (NickGerleman) 
- [ ] Send reminder mail to the team about backport triage (NickGerleman)
-----
**Before Release**
- [ ] Ensure any community typing changes happen (NickGerleman)
- [ ] Ensure doc issues are addressed (???)
- [ ] Promote `latest` build to `legacy` using [wiki instructions](https://github.com/microsoft/react-native-windows/wiki/How-to-promote-a-release) (NickGerleman)
- [ ] Ensure all issues marked with "Blocking Label" are fixed (chrisglein)
-----
**Release**
- [ ] Update preview release notes with any changes from cherry-picked PRs (NickGerleman)
- [ ] Update sample repos to new version (jonthysell), see [upgrade procedure](https://github.com/microsoft/react-native-windows-samples/blob/master/samples/README.md#upgrade-procedure)
- [ ] Update gallery to a new version (chiara)
- [ ] Promote `preview` build to `latest` using [wiki instructions](https://github.com/microsoft/react-native-windows/wiki/How-to-promote-a-release) (NickGerleman)
- [ ] Update GitHub release notes to use manually curated notes instead of a changelog (NickGerleman)
- [ ] Flip docs site to 0.66 (???)
- [ ] Update the CI to tell the API doc generation tool to use the 0.66 prefix
- [ ] Send out internal release announcement (NickGerleman) 
- [ ] Tweet/social (stmoy)

**Comment by NickGerleman** [comment]
Draft changelog:
---

We're excited to release our first preview build of `react-native-windows` 0.66! There have been many changes to both `react-native-windows` and `react-native` itself and we would love your feedback on anything that doesn't work as expected.

## How to upgrade

You can view the differences between different versions of C++ applications using a special version of [React Native Upgrade Helper](https://react-native-community.github.io/upgrade-helper/?package=react-native-windows).

Upgrade helper does not yet support C# projects or projects using experimental features. It is recommended to generate a new project using `react-native-windows-init` for projects not supported by Upgrade Helper.

## What's New

- **Fast Hermes in debug builds:** We previously used debug builds of Hermes when you built your application in a debug configuration. We've heard feedback that this impacted usability, and now use an optimized JS engine regardless of whether your application is running in release or debug.

- **Lower power consumption when using timers:** Long running timers, such as those set by `setInterval`, previously required RNW to do work every frame. We've fixed this, to let your application sleep until wake-up time. 

- **Better error UI:** Your bundle failing to load previously showed a blank screen, requiring debugging your application to get actionable feedback. We now show a native redbox UI with the JavaScript exception.

- **Windows 10 SDK version 10.0.19041.0:** We now use the latest Windows SDK, included with Visual Studio. Note that you may still need to install previous SDKs to use community modules that have not yet updated.

- **Improved responsiveness with expensive callbacks:** We now coalesce events for layout and pointer movement to ensure your application stays responsive if JavaScript callbacks are expensive. 

- **More accessibility roles:** We've added support for the `togglebutton` and `header` accessibility roles

- **Autolinking support for more community modules:** React Native Windows has long-supported autolinking, but not all community modules for Windows were built to be compatible. Autolinking now has a heuristic to link any NPM dependencies that are likely Windows community modules.

- **Native console redirection:** You can now redirect the output of the JavaScript `console` object using the `ReactInstanceSettings::NativeLogger` property.

- **JSValue XAML conversion helpers:** We've added additional helpers to `JSValueXaml.h` to make it easier to write ViewManagers that serialize XAML types.

- **Greater BackHandler control:** You can now control whether to handle back events via the React Native BackHandler, or in native code, using `QuirkSettings::SetBackHandlerKind`.

- **Bug-fixes and improvements:** We've made many more fixes across the platform. Expect less crashes, more correct behavior, and more quality of life improvements for developers.

## Breaking Changes

- **Removal of Picker, DatePicker, PickerWindows:** The various versions of Picker were previously deprecated as part of lean-core efforts. These components are removed in 0.66. The [`@react-native-community/datetimepicker`](https://github.com/react-native-datetimepicker/datetimepicker) and [`@react-native-picker/picker`](https://github.com/react-native-picker/picker) community modules can be used for the same functionality.

- **UseExperimentalNuget configuration:** Projects using the `Microsoft.ReactNative` NuGet package should now declare `UseExperimentalNuget` in their `ExperimentalFeatures.props` file instead of their `vcxproj` or `csproj` file.

**Comment by asklar** [comment]
* Updated to WinUI 2.6 (was that new for 66 or if it was in 65?)
* new "Loading" UI, now using WinUI 2.6's ProgressRing control

**Comment by NickGerleman** [comment]
WinUI 2.6 made it into 0.65. https://github.com/microsoft/react-native-windows/releases/tag/react-native-windows_v0.65.0
