### ISSUE TITLE
0.68 Release Status

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#9486]
## Checklist

**Before Preview**
- [x] Draft GitHub release notes from commit log (NickGerleman)
- [x] Promote canary build to preview using [wiki instructions](https://github.com/microsoft/react-native-windows/wiki/How-to-promote-a-release) (NickGerleman)
- [x] Push build to stable branch (NickGerleman)
  - [x] Enable CI schedule for new branch of [CI pipeline](https://dev.azure.com/ms/react-native-windows/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=468&view=Tab_Triggers)
  - [x] Update [dashboard @ms](https://dev.azure.com/ms/react-native-windows/_dashboards/dashboard/28deb05d-f5bb-43e6-8aa9-36ad5e5476fb) with an entry for `CI ${version}`
  - [x] Add release schedule for the new stable branch of [publish pipline](https://dev.azure.com/microsoft/ReactNative/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=63081&view=Tab_Triggers)
  - [x] Update [dashboard @microsoft](https://dev.azure.com/microsoft/ReactNative/_dashboards/dashboard/8ea77a11-83e2-493a-873f-9cd4562f213d) with an entry for `Publish ${version}`
- [x] Update GitHub release notes to use manually curated notes instead of a changelog (NickGerleman)
- [x] Post release notes internally (NickGerleman)
-----
**After Preview**
- [x] Move most issues targeting current release (chrisglein)
- [x] Test updated gallery app using [wiki instructions](https://github.com/microsoft/react-native-gallery/wiki/Manual-Validation-Steps-for-RNW-Release) (chiaramooney)
- [x] Check [CI Runs](https://github.com/microsoft/react-native-windows-samples/actions?query=workflow:*(Upgrade)) for Upgrading Sample Apps (jon)
- [x] Snap Hermes-Windows release (mganandraj)
- [x] Do a pass on API Docs using [wiki instructions](https://github.com/microsoft/react-native-windows/wiki/API-documentation#validating-api-docs-for-a-release) (chiaramooney)
- [x] Integrate any applicable patch/prerelease releases for React Native (chiaramooney) 
-----
**Before Release**
- [x] Ensure doc issues are addressed (chiaramooney)
- [x] Promote `latest` build to `legacy` using [wiki instructions](https://github.com/microsoft/react-native-windows/wiki/How-to-promote-a-release) (chiaramooney)
-----
**Release**
- [x] Update preview release notes with any changes from cherry-picked PRs (chiaramooney)
- [x] microsoft/react-native-windows-samples#673
- [x] microsoft/react-native-gallery#203
- [x] Promote `preview` build to `latest` using [wiki instructions](https://github.com/microsoft/react-native-windows/wiki/How-to-promote-a-release) (chiaramooney)
- [x] Update GitHub release notes to use manually curated notes instead of a changelog (chiaramooney)
- [x] microsoft/react-native-windows-samples#674
- [x] Send out internal release announcement (chiaramooney)
